### ISSUE TITLE
HolonomicDriveController not included in robotpy 2022 update.

### ISSUE THREAD

**Issue by FRC2539** [robotpy/robotpy-wpimath#25]
### Problem description

The holonomic drive controller class was moved this year to wpimath.controller, and it appears to be present in the gen folder. It is absent from the readthedocs and does not appear to be included in the updated library.

I attempted to import the library and then run the sim (I'm aware it does not work right now but it still gives errors). After removing the instances of the HolonomicDriveController it no longer showed the error, so I am under the assumption that it was not included in the 2022 release.

### Operating System

Linux

### Reproducible example code

```text
from wpimath.controller import HolonomicDriveController
```

**Comment by TheTripleV** [comment]
The import for `HolonomicDriveController` was not included in the initial release. #26 will add that back in.

**Comment by virtuald** [comment]
Until an update is released, I believe that you can find it right now at `wpimath._controls._controls.controller.HolonomicDriveController`
