### ISSUE TITLE
[BUG]: TrajectoryParameterizer returns None

### ISSUE THREAD

**Issue by OliverW10** [robotpy/robotpy-wpimath#35]
### Problem description

TrajectoryParameterizer.parameterizeTrajectory() [is meant to return a trajectory](https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryParameterizer.java#L57) but returns None and [appears to have been overwritten to do nothing](https://github.com/robotpy/robotpy-wpimath/blob/main/gen/controls/TrajectoryParameterizer.yml#L13-L22).

### Operating System

Windows

### Installed Python Packages

```text
fresh python 3.8.6 venv with just `robotpy[all] --pre` installed
```

### Reproducible example code

```text
from wpimath.trajectory import TrajectoryParameterizer
from wpimath.spline import CubicHermiteSpline, SplineHelper
from wpimath.geometry import Pose2d
from typing import Tuple
from math import pi

start = Pose2d(1, 1, 0)
end = Pose2d(2, 2, pi/2)

# generate the spline from start and end poses
vec1, vec2 = SplineHelper.cubicControlVectorsFromWaypoints(start, [], end)
spline = CubicHermiteSpline(vec1.x, vec2.x, vec1.y, vec2.y)

# sample the pose and curvature along the spline
points: Tuple[Pose2d, float] = []
for i in range(100):
    points.append(spline.getPoint(i/100))

trajectory = TrajectoryParameterizer.timeParameterizeTrajectory(points, [], 0, 0, 4, 3, False)
print(trajectory) # None
```

**Comment by virtuald** [comment]
lol oops
