### ISSUE TITLE
Units class not implemented

### ISSUE THREAD

**Issue by mrguisamuel** [robotpy/robotpy-wpimath#37]
### Problem description

Following [#49](https://github.com/robotpy/examples/issues/49)
In `statespaceflywheel` [Java example](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java) Robot.java file, it uses the [Units](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/util/Units.html) class for measurement conversion when it calls the `rotationsPerMinuteToRadiansPerSecond` static method.

I don't know if it's very necessary to add...

### Operating System

Windows, MacOS, Linux

### Installed Python Packages

```
robotpy 2023.0.0b7
robotpy-wpimath 2023.0.0b7
```

### Reproducible example code
```java
private static final double kSpinupRadPerSec = Units.rotationsPerMinuteToRadiansPerSecond(500.0);
```

**Comment by virtuald** [comment]
I feel like we did this at one point, but I can't find it.

**Comment by mrguisamuel** [comment]
Is [MathUtll.yml](https://github.com/robotpy/robotpy-wpimath/blob/main/gen/MathUtil.yml) a reference for Utils? It may be a direct reference.

If it isn't, would Python (considering RobotPy) have a similar alternative?

**Comment by virtuald** [comment]
C++ has its own units system, so it doesn't have a units utils equivalent. It would probably make sense to implement our own conversions and put it in wpimath -- I think it would be more performant and maintainable to do them in python instead of C++. Maybe as `wpimath/units.py`.
